### Crear un usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "usuario_id": 1755648916,
  "nombre": "Jeremy Pacho",
  "correo": "alex@gmail.com",
  "password": "alexander",
  "direccion": "OE20-A",
  "telefono": "0964514852"
}


### Mostrar un usuario
GET  http://localhost:3000/usuarios/1755645148
